In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math as m
import statistics as stats
import scipy.stats as sts
alpha = 0.05

from scipy.stats import chi2
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = sns.load_dataset('tips')

In [3]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
data_table = pd.crosstab(df['sex'], df['smoker'])
data_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [5]:
# in chi square test --> observed value and expected value
observed_value=data_table.values  #observed value

In [6]:
# 1st approach --> allowing chi2 itself some expected values 
stats_test, p, dof, expected_value=sts.chi2_contingency(observed_value)

In [7]:
expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [8]:
# x2= (o-e)**2/e 

In [9]:
for i in zip(observed_value, expected_value):   #zip function do basically pair
    print(i)

(array([60, 97], dtype=int64), array([59.84016393, 97.15983607]))
(array([33, 54], dtype=int64), array([33.15983607, 53.84016393]))


In [10]:
chisquare_test=sum([(o-e)**2 / e for o,e in zip(observed_value, expected_value)])

In [11]:
chisquare_stats = chisquare_test[0]+ chisquare_test[1]
chisquare_stats

0.001934818536627623

In [12]:
dof

1

In [13]:
p

1.0

In [14]:
alpha

0.05

In [15]:
chi2_critical = sts.chi2.ppf(1-alpha, df= dof)
chi2_critical

3.841458820694124

In [16]:
if chisquare_stats > chi2_critical:
    print("Reject the H0, there is relationship between two categorical variables")
else:
    print("Failed to reject the H0, no relationship")

Failed to reject the H0, no relationship


In [17]:
# pvalue method
pvalue = 1-sts.chi2.cdf(x=chisquare_stats, df=dof)
pvalue

0.964915107315732

In [18]:
if pvalue<= alpha:
    print("Reject the H0, there is relationship between two categorical variables")
else:
    print("Failed to reject the H0, no relationship")

Failed to reject the H0, no relationship


In [19]:
# another approach 
# no of hours studies daily on a weekly basis
# monday, tuesday, ...,sunday
expected_data=[8,5,6,8,5,7,6]
observed_data= [7,4,7,9,4,8,6]

In [20]:
sum(expected_data), sum(observed_data)

(45, 45)

In [21]:
ch_stats, pvalue =sts.chisquare(observed_data, expected_data)

In [22]:
ch_stats

0.9595238095238094

In [23]:
pvalue

0.9871002325555286

In [24]:
# find the critical value
alpha

0.05

In [25]:
dof = len(observed_data)-1

In [26]:
dof

6

In [27]:
critical_value= sts.chi2.ppf(1-alpha, dof)

In [28]:
critical_value

12.591587243743977

In [29]:
if ch_stats> critical_value:
    print("Reject the H0")
else:
    print("Failed the reject the H0")

Failed the reject the H0


In [30]:
# f test

In [31]:
worker1 = [18,17,20,25,27,55,51,42,46,29]
worker2 = [18,16,22,26,39,51,48,44,58,12]
fstats= np.var(worker1) / np.var(worker2)

In [32]:
fstats

0.743155149934811

In [33]:
df1 = len(worker1)-1
df2 = len(worker1)-1
alpha =0.05

In [34]:
df1, df2

(9, 9)

In [35]:
#  f critical
f_critical = sts.f.ppf(1-alpha, dfn=df1, dfd= df2)

In [36]:
if fstats >= f_critical:
    print("Reject the H0")
else:
    print("Failed to reject the H0")

Failed to reject the H0


In [37]:
# ANOVA test

In [38]:
# to compare two or more than two means

In [54]:
df = pd.read_excel("plant.xlsx")

In [55]:
df

unamed:  0  wieght  group
0            1    4.17   ctrl
1            2    5.58   ctrl
2            3    5.18   ctrl
3            4    6.11   ctrl
4            5    4.50   ctrl
5            6    4.61   ctrl
6            7    5.17   ctrl
7            8    4.53   ctrl
8            9    5.33   ctrl
9           10    5.14  trt1 
10          11    4.81  trt1 
11          12    4.17  trt1 
12          13    4.41  trt1 
13          14    3.59  trt1 
14          15    5.87   trt1
15          16    3.83   trt1
16          17    6.03   trt1
17          18    4.89   trt1
18          19    4.32   trt1
19          20    4.69   trt1
20          21    6.31   trt2
21          22    5.12   trt2
22          23    5.54   trt2
23          24    5.50   trt2
24          25    5.37   trt2
25          26    5.29   trt2
26          27    4.92   trt2
27          28    5.80   trt2
28          29    5.26   trt2

In [56]:
df.drop("unamed:  0", axis =1, inplace=True)
# print(df.columns)

In [57]:
df

wieght  group
0     4.17   ctrl
1     5.58   ctrl
2     5.18   ctrl
3     6.11   ctrl
4     4.50   ctrl
5     4.61   ctrl
6     5.17   ctrl
7     4.53   ctrl
8     5.33   ctrl
9     5.14  trt1 
10    4.81  trt1 
11    4.17  trt1 
12    4.41  trt1 
13    3.59  trt1 
14    5.87   trt1
15    3.83   trt1
16    6.03   trt1
17    4.89   trt1
18    4.32   trt1
19    4.69   trt1
20    6.31   trt2
21    5.12   trt2
22    5.54   trt2
23    5.50   trt2
24    5.37   trt2
25    5.29   trt2
26    4.92   trt2
27    5.80   trt2
28    5.26   trt2

In [58]:
groups= df.group.unique()
groups

array(['ctrl', 'trt1 ', 'trt1', 'trt2'], dtype=object)

In [59]:
data = {grp: df['wieght'] [df.group==grp] for grp in groups }
data

{'ctrl': 0    4.17
 1    5.58
 2    5.18
 3    6.11
 4    4.50
 5    4.61
 6    5.17
 7    4.53
 8    5.33
 Name: wieght, dtype: float64,
 'trt1 ': 9     5.14
 10    4.81
 11    4.17
 12    4.41
 13    3.59
 Name: wieght, dtype: float64,
 'trt1': 14    5.87
 15    3.83
 16    6.03
 17    4.89
 18    4.32
 19    4.69
 Name: wieght, dtype: float64,
 'trt2': 20    6.31
 21    5.12
 22    5.54
 23    5.50
 24    5.37
 25    5.29
 26    4.92
 27    5.80
 28    5.26
 Name: wieght, dtype: float64}

In [60]:
data['ctrl']

0    4.17
1    5.58
2    5.18
3    6.11
4    4.50
5    4.61
6    5.17
7    4.53
8    5.33
Name: wieght, dtype: float64

In [64]:
f_stats, pvalue= sts.f_oneway(data['ctrl'],data['trt1'],data['trt2'])

In [65]:
f_stats, pvalue

(1.6349288372121684, 0.2188248728866687)

In [66]:
if pvalue <= 0.05:
    print("Reject the H0")
else:
    print("Failed to reject the H0")

Failed to reject the H0
